version: '3.9'
services:
  edu-cloud-gateway:
    image: edu:1.0
    container_name: edu-cloud-gateway
    ports:
      - 8080:8080
    env_file:
      - app.env
    volumes:
      - /home/edu/api/edu-cloud-gateway.jar:/app/app.jar
  edu-cloud-system:
    image: edu:1.0
    container_name: edu-cloud-system
    env_file:
      - app.env
    volumes:
      - /home/edu/api/edu-cloud-system.jar:/app/app.jar
