spring:
  redis:
    database: 2
    host: *.*.*.*
    port: 6379
    password: pwd@123
  rabbitmq:
    addresses: *.*.*.*:5672
    username: guest
    password: 
    publisher-returns: true
    publisher-confirm-type: correlated
    virtual-host: /
    listener:
      type: simple
      simple:
        acknowledge-mode: manual #确认模式
        prefetch: 1 #限制每次发送一条数据。
        concurrency: 3 #同一个队列启动几个消费者
        max-concurrency: 10 #启动消费者最大数量
        #重试策略相关配置
        retry:
          # 开启消费者(程序出现异常)重试机制，默认开启并一直重试
          enabled: true
          # 最大重试次数
          max-attempts: 1
          # 重试间隔时间(毫秒)
          initial-interval: 3000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://*.*.*.*:3306/edu_cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: pwd@123
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 5
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: net.edu.*.entity
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
storage:
  enabled: true
  config:
    # 存储类型：local、aliyun
    type: local
    # 访问域名
    domain: http://127.0.0.1:8080/file
    # 配置访问前缀
    prefix: upload
  local:
    # 本地上传路径
    path: E://upload
    samplePath: E://sample
    templatePath: E://template